azureproject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("trips/", include("trips.urls")),
    path("admin/", admin.site.urls),
]

trips/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:trip_id>/", views.detail, name="detail"),
    path("flights/<int:id>/change/", views.flight_update, name="flight_update"),
    path("budgets/<int:id>/change/", views.budget_update, name="budget_update"),
    path("attractions/<int:id>/change/", views.attraction_update, name="attraction_update"),
    path("flights/add/", views.flight_add, name="flight_add"),
    path("budgets/add/", views.budget_add, name="budget_add"),
    path("attractions/add/", views.attraction_add, name="attraction_add"),
    path("add/", views.trip_add, name="trip_add"),
]

trips/models.py
from django.db import models

# Create your models here.
from django.db import models

budget_choices = [('f','food'),('l','lodging'),('t','transportation'),('e','entertainment'),('o','other')]

class Trip(models.Model):
    city = models.CharField(max_length=200)
    state = models.CharField(max_length=200)
    country = models.CharField(max_length=200,default='US')
    arrive_dt = models.DateTimeField("arrival date")
    depart_dt = models.DateTimeField("departure date")
    lodging = models.CharField(max_length=200)
    notes = models.CharField(max_length=200, blank=True, null=True)
    
    def __str__(self):
        return self.city
    


class Budget(models.Model):
    trip = models.ForeignKey(Trip, on_delete=models.CASCADE)
    item = models.CharField(max_length=200)
    item_type = models.CharField(max_length=200, choices=budget_choices)
    cost = models.IntegerField(default=0)
    
    def __str__(self):
        return str(self.trip) + ' - ' + self.item
    
class Flight(models.Model):
    trip = models.ForeignKey(Trip, on_delete=models.CASCADE)
    airline = models.CharField(max_length=200)
    airports = models.CharField(max_length=200)
    arrive_time = models.DateTimeField("time of flight")
    depart_time = models.DateTimeField("time of return")
    notes = models.CharField(max_length=200, blank=True, null=True)
    
    def __str__(self):
        return str(self.trip) + ' - ' + self.airline
    
class Attraction(models.Model):
    trip = models.ForeignKey(Trip, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    address = models.CharField(max_length=200, blank=True, null=True)
    url = models.CharField(max_length=200, blank=True, null=True)
    item_type = models.CharField(max_length=200, choices=budget_choices, default=budget_choices[0])
    type = models.CharField(max_length=200)
    notes = models.CharField(max_length=200, blank=True, null=True)
    confirmed = models.BooleanField(default=False)
    cost = models.IntegerField(blank=True, null=True)
    
    def __str__(self):
        return str(self.trip) + ' - ' + self.name

trips/forms.py
from django.forms import ModelForm, widgets
from django import forms
from .models import Trip, Budget, Flight, Attraction

budget_choices = [('f','food'),('l','lodging'),('t','transportation'),('e','entertainment'),('o','other')]

# Create the form class.
class FlightForm(ModelForm):
    class Meta:
        model = Flight
        trip = forms.ModelChoiceField(queryset=Trip.objects.all())
        fields = '__all__'
        widgets = {
            'arrive_time': widgets.DateTimeInput(attrs={'type': 'datetime-local'}),
            'depart_time': widgets.DateTimeInput(attrs={'type': 'datetime-local'})
        }
        
class TripForm(ModelForm):
    class Meta:
        model = Trip
        fields = '__all__'
        widgets = {
            'arrive_dt': widgets.DateTimeInput(attrs={'type': 'datetime-local'}),
            'depart_dt': widgets.DateTimeInput(attrs={'type': 'datetime-local'})
        }
        
class BudgetForm(ModelForm):
    class Meta:
        model = Budget
        trip = forms.ModelChoiceField(queryset=Trip.objects.all())
        item_type = forms.ChoiceField(choices=budget_choices)
        fields = '__all__'
        
class AttractionForm(ModelForm):
    class Meta:
        model = Attraction
        trip = forms.ModelChoiceField(queryset=Trip.objects.all())
        item_type = forms.ChoiceField(choices=budget_choices)
        fields = '__all__'
        

trips/views.py
from django.shortcuts import render, redirect
from django.template import loader
from django.db.models import Sum


# Create your views here.
from django.http import Http404
from .models import Trip, Budget, Flight, Attraction
from .forms import FlightForm, BudgetForm, AttractionForm, TripForm


def trip_add(request):
    if request.method == 'POST':
        form = TripForm(request.POST)
        if form.is_valid():
            # create a new `Band` and save it to the db
            trip = form.save()
            # redirect to the detail page of the band we just created
            # we can provide the url pattern arguments as arguments to redirect function
            return redirect('detail', trip.id)

    else:
        form = TripForm()

    return render(request,
                'trips/trip_add.html',
                {'form': form})

def index(request):
    latest_trip_list = Trip.objects.order_by("-arrive_dt")[:5]
    context = {
        "latest_trip_list": latest_trip_list,
    }
    return render(request, "trips/index.html", context)

def detail(request, trip_id):
    try:
        trip = Trip.objects.get(pk=trip_id)
        try:
            budgets = Budget.objects.filter(trip__pk=trip_id)
            b_cnt = Budget.objects.filter(trip__pk=trip_id).count()
            b_sum = budgets.aggregate(Sum("cost"))["cost__sum"]
        except:
            budgets = None
            b_cnt = None
            b_sum = None
        try:
            flights = Flight.objects.filter(trip__pk=trip_id)
            
        except:
            flights = None
        try:
            attractions = Attraction.objects.filter(trip__pk=trip_id)
            a_cnt = Attraction.objects.filter(trip__pk=trip_id).count()
            a_sum = attractions.aggregate(Sum("cost"))["cost__sum"]
            
        except:
            attractions = None
            a_cnt = None
            a_sum = None
    except:
        raise Http404("trip not found")
    context = {
        "trip": trip,
        "budgets": budgets,
        "flights": flights,
        "attractions": attractions,
        "a_cnt": a_cnt,
        "a_sum": a_sum,
        "b_cnt": b_cnt,
        "b_sum": b_sum,
    }
    return render(request, "trips/detail.html",context)


def flight_add(request):
    if request.method == 'POST':
        form = FlightForm(request.POST)
        if form.is_valid():
            # create a new `Band` and save it to the db
            flight = form.save()
            # redirect to the detail page of the band we just created
            # we can provide the url pattern arguments as arguments to redirect function
            return redirect('detail', flight.trip_id)

    else:
        form = FlightForm()

    return render(request,
                'trips/flight_add.html',
                {'form': form})


def flight_update(request, id):
    flight = Flight.objects.get(id=id)
    if request.method == 'POST':
        form = FlightForm(request.POST, instance=flight)
        if form.is_valid():
        # update the existing `Band` in the database
            form.save()
        # redirect to the detail page of the `Band` we just updated
            return redirect('detail', flight.trip_id)
    else:
            form = FlightForm(instance=flight) # prepopulate the form with an existing band
    return render(request,
                    'trips/flight_update_form.html',
                    {'form': form})
    
def budget_add(request):
    if request.method == 'POST':
        form = BudgetForm(request.POST)
        if form.is_valid():
            # create a new `Band` and save it to the db
            budget = form.save()
            # redirect to the detail page of the band we just created
            # we can provide the url pattern arguments as arguments to redirect function
            return redirect('detail', budget.trip_id)

    else:
        form = BudgetForm()

    return render(request,
                'trips/budget_add.html',
                {'form': form})
    
def budget_update(request, id):
    budget = Budget.objects.get(id=id)
    if request.method == 'POST':
        form = BudgetForm(request.POST, instance=budget)
        if form.is_valid():
        # update the existing `Band` in the database
            form.save()
        # redirect to the detail page of the `Band` we just updated
            return redirect('detail', budget.trip_id)
    else:
            form = BudgetForm(instance=budget) # prepopulate the form with an existing band
    return render(request,
                    'trips/budget_update_form.html',
                    {'form': form})

def attraction_add(request):
    if request.method == 'POST':
        form = AttractionForm(request.POST)
        if form.is_valid():
            # create a new `Band` and save it to the db
            attraction = form.save()
            # redirect to the detail page of the band we just created
            # we can provide the url pattern arguments as arguments to redirect function
            return redirect('detail', attraction.trip_id)

    else:
        form = AttractionForm()

    return render(request,
                'trips/attraction_add.html',
                {'form': form})
    
def attraction_update(request, id):
    attraction = Attraction.objects.get(id=id)
    if request.method == 'POST':
        form = AttractionForm(request.POST, instance=attraction)
        if form.is_valid():
        # update the existing `Band` in the database
            form.save()
        # redirect to the detail page of the `Band` we just updated
            return redirect('detail', attraction.trip_id)
    else:
            form = AttractionForm(instance=attraction) # prepopulate the form with an existing band
    return render(request,
                    'trips/budget_add.html',
                    {'form': form})

trips/templates/trips/attraction_add.html
<h1>Create new Attraction Item</h1>

<form action="" method="post" novalidate>
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Submit">
</form>

trips/templates/trips/base.html
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Trip Planner</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" rel="stylesheet">
  </head>
  <body>
    
    {% comment %} <nav class="navbar navbar-expand-lg navbar-light bg-dark">
        <a class="navbar-brand" href="https://tifftrips.azurewebsites.net/trips/">Tiff Trips</a>
        
        
           
             
         
      </nav> {% endcomment %}
    
    {% block content %}
      <!-- default content text (typically empty) -->
    {% endblock %}
  </body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</html>

trips/templates/trips/budget_add.html
<h1>Create new Budget Item</h1>

<form action="" method="post" novalidate>
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Submit">
</form>

trips/templates/trips/budget_update_form.html
<h1>Update Flight</h1>

  <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
 </form>

trips/templates/trips/detail.html
{% extends "base.html" %}

{% block content %}
<body>
<div class="container-fluid text-dark">
    <div class="row text-center mb-5">
       
                <div>
                    <h1>{{ trip }}</h1>
                </div>
                <div>
                 
                        <div>state: {{ trip.state }}</div>
                        <div>arrival date: {{ trip.arrive_dt | date:"M d, Y" }}</div>
                        <div>departure date: {{ trip.depart_dt | date:"M d, Y" }}</div>
                   
                </div>
           
        
    </div>
    <div class="row">
    <div class="col-md-4 bg-light border rounded-3">
        <a class="btn btn-primary bg-gradient" data-bs-toggle="collapse" href="#multiCollapseExample2" role="button" aria-expanded="false" aria-controls="multiCollapseExample2">flights</a>
        <a href="/trips/flights/add/"><i class="fa-solid fa-plus"></i></a>
       
            
        {% if flights %}
            <div class="collapse multi-collapse" id="multiCollapseExample2">
            {% for f in flights %}
            <ul class="border rounded 5">
            <a href="/trips/flights/{{ f.id }}/change/"> {{ f }} </a>
                <li>Airline: {{ f.airline }} </li>
                <li>Airports: {{ f.airports }} </li>
                <li>Departs: {{ f.arrive_time | date:"h:i A" }} </li>
                <li>Lands: {{ f.depart_time | date:"h:i A" }} </li>
                <li>Notes: {{ f.notes }} </li>
            </ul>
            {% endfor %}
        </div>
    </div>
            {% else %}
    <p>No trips are available.</p>
{% endif %}
     
     <div class="col-md-4 border bg-light rounded-3">
        <a class="btn btn-primary bg-gradient text-light" data-bs-toggle="collapse" href="#multiCollapseExample1" role="button" aria-expanded="false" aria-controls="multiCollapseExample1">Budgets</a>
        <a href="/trips/budgets/add/"><i class="fa-solid fa-plus"></i></a>
        <p style="float:right" class="card bg-warning rounded-3 ps-1 pe-1""> Cost: {{ b_sum }}</p>
        <p style="float:right" class="card bg-warning rounded-3 me-3 ps-1 pe-1"># of items: {{ b_cnt }}</p>  
        {% if budgets %}
            <div class="collapse multi-collapse" id="multiCollapseExample1">
            {% for f in budgets %}
            <ul class="border rounded 5">
                <a href="/trips/budgets/{{ f.id }}/change/"> {{ f }} </a>
                <li>category: {{ f.get_item_type_display }} </li>
                <li>Cost: {{ f.cost }} </li>
                
            </ul>
            {% endfor %}
            </div>
            {% else %}
    <p>No trips are available.</p>
{% endif %}
     </div>
     <div class="col-md-4 border bg-light rounded-3">
        <div syle="inline-block">
        <a class="btn btn-primary bg-gradient" data-bs-toggle="collapse" href="#multiCollapseExample3" role="button" aria-expanded="false" aria-controls="multiCollapseExample3">Attractions</a>
        <a href="/trips/attractions/add/"><i class="fa-solid fa-plus"></i></a>
        <p style="float:right" class="card bg-warning rounded-3 ps-1 pe-1""> Cost: {{ a_sum }}</p>
        <p style="float:right" class="card bg-warning rounded-3 me-3 ps-1 pe-1"> {{ a_cnt }} total attractions</p>  
        </div>
       
        {% if attractions %}
            <div class="collapse multi-collapse border rounded 5" id="multiCollapseExample3">
            {% for f in attractions %}
            <ul class="border rounded 5">
                <a href="/trips/attractions/{{ f.id }}/change/"> {{ f }} </a>
                <li>category: {{ f.get_item_type_display }} </li>
                <li>Cost: {{ f.cost }} </li>
                <li><a href="{{ f.url }}"> {{ f.url }}</a> 
                <li>Confirmed: {{ f.confirmed }} </li>
                <li>Notes: {{ f.notes }} </li>
                
                
            </ul>

            {% endfor %}
        </div>
            {% else %}
    <p>No trips are available.</p>
{% endif %}
     </div>
    </div>

</div>


{% endblock %}

trips/templates/trips/flight_add.html
<h1>Create new flight</h1>

<form action="" method="post" novalidate>
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Submit">
</form>

trips/templates/trips/flight_update_form.html
<h1>Update Flight</h1>

  <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
 </form>

trips/templates/trips/index.html
{% extends "base.html" %}
{% block content %}
        <div class="container-fluid">

        <!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
    Tiff
  </button>
  
  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">To My Baby</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRL23RRedvPfr5hA0pyDfgxR-nDDhrx0PNITg&usqp=CAU" alt="Girl in a jacket" width="300" height="300">
            <p>Tiffany I love you and think about you everyday. I hope whatever you are doing right now that you are happy because you deserve the world bb. I'll never meet someone with a bigger heart than you and no one will ever be able to fill the place you took in mine. Dont ever change babe - you are perfect how you are. </p>


        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
{% if latest_trip_list %}
    <ul>
    {% for trip in latest_trip_list %}
        <li><a href="/trips/{{ trip.id }}/">{{ trip.city }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No trips are available.</p>
{% endif %}
</div>
{% endblock %}

trips/templates/trips/trip_add.html
<h1>Create new trip</h1>

<form action="" method="post" novalidate>
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Submit">
</form>